=== Darathor/Change/Change/Documents/Assets/document.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://www.rbs.fr/schema/change-document/4.0"
		   xmlns="http://www.rbs.fr/schema/change-document/4.0">

	<!--
		This file is published on http://www.rbschange.fr/schema/4.0/document.xsd
	-->

	<xs:simpleType name="propertyType">
		<xs:annotation>
			<xs:documentation source="version">4.0</xs:documentation>
			<xs:documentation source="description">
				A property type : String | Boolean | Integer | Float | Decimal |
				Date | DateTime | LongString | XML | Lob | RichText | JSON | Object
				DocumentId | Document | DocumentArray
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="String"/>
			<xs:enumeration value="Boolean"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="Float"/>
			<xs:enumeration value="Decimal"/>
			<xs:enumeration value="Date"/>
			<xs:enumeration value="DateTime"/>
			<xs:enumeration value="LongString"/>
			<xs:enumeration value="XML"/>
			<xs:enumeration value="Lob"/>
			<xs:enumeration value="RichText"/>
			<xs:enumeration value="JSON"/>
			<xs:enumeration value="Object"/>
			<xs:enumeration value="DocumentId"/>
			<xs:enumeration value="Document"/>
			<xs:enumeration value="DocumentArray"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="documentModel">
		<xs:annotation>
			<xs:documentation source="version">4.0</xs:documentation>
			<xs:documentation source="description">
				a document model name : [A-Z][a-z0-9]+_[A-Z][a-z0-9]+_[A-Z][A-Za-z0-9]+
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][a-z0-9]+_[A-Z][a-z0-9]+_[A-Z][A-Za-z0-9]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="treeName">
		<xs:annotation>
			<xs:documentation source="version">4.0</xs:documentation>
			<xs:documentation source="description">
				a tree name : ([A-Z][a-z0-9]+_[A-Z][a-z0-9]+)|(false)|(true)
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="([A-Z][a-z0-9]+_[A-Z][a-z0-9]+)|(false)|(true)"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="indexTarget">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="none"/>
			<xs:enumeration value="property"/>
			<xs:enumeration value="description"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="dbOptions">
		<xs:attribute name="length" use="optional" type="xs:integer" default="255">
			<xs:annotation>
				<xs:documentation source="description">use by 'String' property</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="precision" use="optional" type="xs:integer" default="13">
			<xs:annotation>
				<xs:documentation source="description">use by 'Decimal' property</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="scale" use="optional" type="xs:integer" default="4">
			<xs:annotation>
				<xs:documentation source="description">use by 'Decimal' property</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="constraint">
		<xs:attribute name="name" use="required" type="xs:string"/>

		<xs:attribute name="min" use="optional" type="xs:double">
			<xs:annotation>
				<xs:documentation source="description">use by 'min', 'minSize' and 'range' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="max" use="optional" type="xs:double">
			<xs:annotation>
				<xs:documentation source="description">use by 'max', 'maxSize' and 'range' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="inclusive" use="optional" type="xs:boolean">
			<xs:annotation>
				<xs:documentation source="description">use by 'range' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="fromList" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'enum' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="values" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'enum' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="modelName" use="optional" type="documentModel">
			<xs:annotation>
				<xs:documentation source="description">use by 'unique' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="propertyName" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'unique' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="documentId" use="optional" type="xs:unsignedLong">
			<xs:annotation>
				<xs:documentation source="description">use by 'unique' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="pattern" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'matches' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="message" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'matches' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="allow" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'hostname' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:element name="document">
		<xs:annotation>
			<xs:documentation source="version">4.0</xs:documentation>
			<xs:documentation source="description">
				The document element is the root element.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="properties" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dboptions" type="dbOptions" minOccurs="0" maxOccurs="1"/>
										<xs:element name="constraint" type="constraint" minOccurs="0" maxOccurs="10"/>
									</xs:sequence>
									<xs:attribute name="name" use="required" type="xs:string"/>
									<xs:attribute name="type" use="optional" type="propertyType" default="String"/>
									<xs:attribute name="document-type" type="documentModel"/>
									<xs:attribute name="indexed" type="indexTarget" default="none"/>
									<xs:attribute name="cascade-delete" type="xs:boolean" default="true"/>
									<xs:attribute name="default-value" type="xs:string"/>
									<xs:attribute name="required" type="xs:boolean" default="true"/>
									<xs:attribute name="min-occurs" type="xs:int" default="2"/>
									<xs:attribute name="max-occurs" type="xs:int" default="10"/>
									<xs:attribute name="localized" type="xs:boolean" default="true"/>
									<xs:attribute name="has-correction" type="xs:boolean" default="true"/>

									<!-- stateless exclude: cascade-delete, has-correction. -->
									<xs:attribute name="stateless" type="xs:boolean" default="true"/>

									<xs:attribute name="abstract" type="xs:boolean" default="true"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
			<xs:attribute name="icon" type="xs:string"/>

			<xs:attribute name="has-url" type="xs:boolean" default="true"/>
			<xs:attribute name="frontoffice-indexable" type="xs:boolean" default="true"/>
			<xs:attribute name="backoffice-indexable" type="xs:boolean" default="false"/>

			<xs:attribute name="extends" type="documentModel"/>
			<xs:attribute name="replace" type="xs:boolean" default="false"/>

			<xs:attribute name="localized" type="xs:boolean" default="true"/>
			<xs:attribute name="editable" type="xs:boolean" default="true"/>
			<xs:attribute name="publishable" type="xs:boolean" default="true"/>
			<xs:attribute name="use-version" type="xs:boolean" default="true"/>
			<xs:attribute name="tree-name" type="treeName" default="true"/>

			<!-- stateless exclude: extends, inject, has-url, frontoffice-indexable, backoffice-indexable,
					localized, editable, publishable, use-version. -->
			<xs:attribute name="stateless" type="xs:boolean" default="true"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Darathor/Change/Plugins/Modules/Rbs/Catalog/Documents/Assets/Attribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"
		editable="true" localized="true">
	<properties>
		<property name="title" type="String" localized="true" has-correction="true"/>
		<property name="description" type="RichText" localized="true" has-correction="true"/>
		<property name="valueType" type="String" default-value="String" required="true">
			<dboptions length="16" />
			<constraint name="enum" fromList="Rbs_Catalog_Collection_AttributeValueTypes" />
		</property>
		<property name="requiredValue" type="Boolean" default-value="false" />
		<property name="defaultValue" type="String" />
		<property name="localizedValue" type="Boolean" default-value="false" />
		<property name="collectionCode" type="String" >
			<dboptions length="100" />
		</property>
		<property name="productProperty" type="String" />
		<property name="attributes" type="DocumentArray" document-type="Rbs_Catalog_Attribute" />
		<property name="visibility" type="JSON" />
		<property name="documentType" type="String" />
		<property name="axis" type="Boolean" default-value="false" />

		<property name="usePicker" type="Boolean" default-value="false" />

		<property name="productTypology" type="Boolean" default-value="false" />
	</properties>
</document>

=== Darathor/Change/Plugins/Modules/Rbs/Order/Documents/Assets/Order.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"
	editable="true">
	<properties>
		<property name="label" stateless="true" />
		<property name="ownerId" type="DocumentId" />

		<property name="code" type="String" />
		<property name="webStoreId" type="DocumentId" document-type="Rbs_Store_WebStore"/>
		<property name="billingAreaId" type="DocumentId" document-type="Rbs_Price_BillingArea"/>
		<property name="contextData" type="JSON" />

		<property name="linesData" type="JSON" />
		<property name="addressData" type="JSON" />
		<property name="shippingData" type="JSON" />

		<property name="amount" type="Decimal" />
		<property name="amountWithTax" type="Decimal" />
		<property name="currencyCode" type="String">
			<dboptions length="3" />
		</property>

		<property name="closed" type="Boolean" default-value="false"/>

	</properties>
</document>

=== Darathor/Change/Plugins/Modules/Change/Users/Documents/Assets/User.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"	
	icon="user-frontoffice" editable="true" publishable="true" >
	<properties>
		<property name="label">
			<constraint name="pseudonym" />
		</property>
		<property name="email" type="String" required="true">
			<constraint name="email" />
		</property>
		<property name="isroot" type="Boolean" default-value="false" />
		<property name="issudoer" type="Boolean" default-value="false" />
		<property name="login" type="String" required="true">
			<constraint name="login" />
		</property>
		<property name="passwordmd5" type="String" indexed="none" required="true">
			<constraint name="maxSize" max="50" />
		</property>
		<property name="groups" type="DocumentArray" document-type="Change_Users_Group" />
		<property name="lastlogin" type="DateTime" />
		<property name="lastping" type="DateTime" />
		<property name="changepasswordkey" type="String" indexed="none">
			<constraint name="maxSize" max="50" />
		</property>
	</properties>
</document>

=== Darathor/Change/ChangeTests/UnitTestWorkspace/App/Modules/Project/Tests/Documents/Assets/Basic.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 https://raw.github.com/RBSChange/Change/master/Change/Documents/Assets/document.xsd"
	tree-name="Project_Tests">
	<properties>
		<property name="pStr" type="String" required="true"/>
		<property name="pBool" type="Boolean" />
		<property name="pInt" type="Integer" />
		<property name="pFloat" type="Float" />
		<property name="pDec" type="Decimal" />
		<property name="pDa" type="Date" />
		<property name="pDaTi" type="DateTime" />
		<property name="pText" type="LongString" />
		<property name="pJson" type="JSON" />
		<property name="pRt" type="RichText" />
		<property name="plob" type="Lob" />
		<property name="pDocId" type="DocumentId" />
		<property name="pStorUri" type="StorageUri" />
		<property name="pDocInst" type="Document" document-type="Project_Tests_Localized" />
		<property name="pDocArr" type="DocumentArray" document-type="Project_Tests_Localized"/>
	</properties>
</document>

=== Darathor/Change/Plugins/Modules/Rbs/Payment/Documents/Assets/Transaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"
	editable="true">
	<properties>
		<property name="label" stateless="true" />
		<property name="email" type="String" />
		<property name="ownerId" type="DocumentId" />
		<property name="targetIdentifier" type="String" />
		<property name="contextData" type="JSON" />
		<property name="amount" type="Decimal" />
		<property name="currencyCode" type="String">
			<dboptions length="3" />
		</property>
		<property name="processingStatus" type="String" default-value="initiated">
			<dboptions length="10" />
			<constraint name="enum" values="initiated,processing,success,failed" />
		</property>
		<property name="connector" type="Document" document-type="Rbs_Payment_Connector" />
		<property name="processingIdentifier" type="String" />
		<property name="processingDate" type="DateTime" />
		<property name="processingData" type="JSON" />
	</properties>
</document>

=== Darathor/Change/Plugins/Modules/Rbs/User/Documents/Assets/Group.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd" 
	icon="user" has-url="false" editable="true">
	<properties>
		<property name="realm" type="String">
			<dboptions length="128" />
		</property>

		<property name="identifier" type="String">
			<dboptions length="50" />
			<constraint name="maxSize" max="50" />
			<constraint name="unique" />
			<constraint name="matches" pattern="/^[a-z][a-z0-9_\-]{1,49}$/" />
		</property>
	</properties>
</document>

=== Darathor/Change/ChangeTests/UnitTestWorkspace/App/Modules/Project/Tests/Documents/Assets/Correction.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 https://raw.github.com/RBSChange/Change/master/Change/Documents/Assets/document.xsd"
          icon="correction" backoffice-indexable="false" localized="true" publishable="true" editable="true">
    <properties>
        <property name="label">
            <dboptions length="40" />
            <constraint name="maxSize" max="40" />
        </property>
        <property name="str1" type="String"/>
        <property name="str2" type="String" has-correction="true"/>

        <property name="str3" type="String" localized="true"/>
        <property name="str4" type="String" localized="true" has-correction="true"/>

        <property name="docs1" type="DocumentArray" document-type="Project_Tests_Basic" max-occurs="2"/>
        <property name="docs2" type="DocumentArray" document-type="Project_Tests_Basic" has-correction="true"/>
    </properties>
</document>

=== Darathor/Change/Plugins/Modules/Rbs/Simpleform/Documents/Assets/Form.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"
	publishable="true" localized="true" editable="true">
	<properties>
		<property name="title" has-correction="true" />
		<property name="publicationSections" type="DocumentArray" document-type="Rbs_Website_Section" />
		<property name="fields" type="InlineArray" has-correction="true">
			<inline name="FormField" localized="true" editable="true">
				<properties>
					<property name="name" type="String" required="true" />
					<property name="title" type="String" localized="true" />
					<property name="helpText" type="RichText" localized="true" />
					<property name="fieldTypeCode" type="String" required="true" />
					<property name="required" type="Boolean" default-value="false" />
					<property name="parameters" type="JSON" />
				</properties>
			</inline>
		</property>
		<property name="receiverUsers" type="DocumentArray" document-type="Rbs_User_User" />
		<property name="receiverGroups" type="DocumentArray" document-type="Rbs_User_Group" />
		<property name="receiverEmails" type="LongString">
			<constraint name="emails" />
		</property>
		<property name="confirmationMode" type="String" has-correction="true" default-value="message" />
		<property name="confirmationMessage" type="RichText" localized="true" has-correction="true" />
		<property name="confirmationPage" type="Document" document-type="Rbs_Website_StaticPage" has-correction="true" />
		<property name="useCaptcha" type="Boolean" default-value="true" has-correction="true" />
		<property name="sendAcknowledgment" type="Boolean" default-value="false" />
		<property name="saveResponses" type="Boolean" default-value="true" />
	</properties>
</document>
