=== Darathor/Change/Change/Documents/Assets/document.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://www.rbs.fr/schema/change-document/4.0"
		   xmlns="http://www.rbs.fr/schema/change-document/4.0">

	<!--
		This file is published on http://www.rbschange.fr/schema/4.0/document.xsd
	-->

	<xs:simpleType name="propertyType">
		<xs:annotation>
			<xs:documentation source="version">4.0</xs:documentation>
			<xs:documentation source="description">
				A property type : String | Boolean | Integer | Float | Decimal |
				Date | DateTime | LongString | XML | Lob | RichText | JSON | Object
				DocumentId | Document | DocumentArray
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="String"/>
			<xs:enumeration value="Boolean"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="Float"/>
			<xs:enumeration value="Decimal"/>
			<xs:enumeration value="Date"/>
			<xs:enumeration value="DateTime"/>
			<xs:enumeration value="LongString"/>
			<xs:enumeration value="XML"/>
			<xs:enumeration value="Lob"/>
			<xs:enumeration value="RichText"/>
			<xs:enumeration value="JSON"/>
			<xs:enumeration value="Object"/>
			<xs:enumeration value="DocumentId"/>
			<xs:enumeration value="Document"/>
			<xs:enumeration value="DocumentArray"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="documentModel">
		<xs:annotation>
			<xs:documentation source="version">4.0</xs:documentation>
			<xs:documentation source="description">
				a document model name : [A-Z][a-z0-9]+_[A-Z][a-z0-9]+_[A-Z][A-Za-z0-9]+
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][a-z0-9]+_[A-Z][a-z0-9]+_[A-Z][A-Za-z0-9]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="treeName">
		<xs:annotation>
			<xs:documentation source="version">4.0</xs:documentation>
			<xs:documentation source="description">
				a tree name : ([A-Z][a-z0-9]+_[A-Z][a-z0-9]+)|(false)|(true)
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="([A-Z][a-z0-9]+_[A-Z][a-z0-9]+)|(false)|(true)"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="indexTarget">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="none"/>
			<xs:enumeration value="property"/>
			<xs:enumeration value="description"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="dbOptions">
		<xs:attribute name="length" use="optional" type="xs:integer" default="255">
			<xs:annotation>
				<xs:documentation source="description">use by 'String' property</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="precision" use="optional" type="xs:integer" default="13">
			<xs:annotation>
				<xs:documentation source="description">use by 'Decimal' property</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="scale" use="optional" type="xs:integer" default="4">
			<xs:annotation>
				<xs:documentation source="description">use by 'Decimal' property</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="constraint">
		<xs:attribute name="name" use="required" type="xs:string"/>

		<xs:attribute name="min" use="optional" type="xs:double">
			<xs:annotation>
				<xs:documentation source="description">use by 'min', 'minSize' and 'range' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="max" use="optional" type="xs:double">
			<xs:annotation>
				<xs:documentation source="description">use by 'max', 'maxSize' and 'range' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="inclusive" use="optional" type="xs:boolean">
			<xs:annotation>
				<xs:documentation source="description">use by 'range' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="fromList" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'enum' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="values" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'enum' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="modelName" use="optional" type="documentModel">
			<xs:annotation>
				<xs:documentation source="description">use by 'unique' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="propertyName" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'unique' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="documentId" use="optional" type="xs:unsignedLong">
			<xs:annotation>
				<xs:documentation source="description">use by 'unique' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="pattern" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'matches' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="message" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'matches' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>

		<xs:attribute name="allow" use="optional" type="xs:string">
			<xs:annotation>
				<xs:documentation source="description">use by 'hostname' constraint</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:element name="document">
		<xs:annotation>
			<xs:documentation source="version">4.0</xs:documentation>
			<xs:documentation source="description">
				The document element is the root element.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="properties" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dboptions" type="dbOptions" minOccurs="0" maxOccurs="1"/>
										<xs:element name="constraint" type="constraint" minOccurs="0" maxOccurs="10"/>
									</xs:sequence>
									<xs:attribute name="name" use="required" type="xs:string"/>
									<xs:attribute name="type" use="optional" type="propertyType" default="String"/>
									<xs:attribute name="document-type" type="documentModel"/>
									<xs:attribute name="indexed" type="indexTarget" default="none"/>
									<xs:attribute name="cascade-delete" type="xs:boolean" default="true"/>
									<xs:attribute name="default-value" type="xs:string"/>
									<xs:attribute name="required" type="xs:boolean" default="true"/>
									<xs:attribute name="min-occurs" type="xs:int" default="2"/>
									<xs:attribute name="max-occurs" type="xs:int" default="10"/>
									<xs:attribute name="localized" type="xs:boolean" default="true"/>
									<xs:attribute name="has-correction" type="xs:boolean" default="true"/>

									<!-- stateless exclude: cascade-delete, has-correction. -->
									<xs:attribute name="stateless" type="xs:boolean" default="true"/>

									<xs:attribute name="abstract" type="xs:boolean" default="true"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
			<xs:attribute name="icon" type="xs:string"/>

			<xs:attribute name="has-url" type="xs:boolean" default="true"/>
			<xs:attribute name="frontoffice-indexable" type="xs:boolean" default="true"/>
			<xs:attribute name="backoffice-indexable" type="xs:boolean" default="false"/>

			<xs:attribute name="extends" type="documentModel"/>
			<xs:attribute name="replace" type="xs:boolean" default="false"/>

			<xs:attribute name="localized" type="xs:boolean" default="true"/>
			<xs:attribute name="editable" type="xs:boolean" default="true"/>
			<xs:attribute name="publishable" type="xs:boolean" default="true"/>
			<xs:attribute name="use-version" type="xs:boolean" default="true"/>
			<xs:attribute name="tree-name" type="treeName" default="true"/>

			<!-- stateless exclude: extends, inject, has-url, frontoffice-indexable, backoffice-indexable,
					localized, editable, publishable, use-version. -->
			<xs:attribute name="stateless" type="xs:boolean" default="true"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Darathor/Change/Plugins/Modules/Rbs/User/Documents/Assets/User.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"
	icon="user-frontoffice" editable="true" activable="true" >
	<properties>
        <property name="email" type="String" required="true">
            <constraint name="email" />
        </property>

        <property name="login" type="String">
            <dboptions length="50" />
            <constraint name="maxSize" max="50" />
			<constraint name="unique" />
			<constraint name="matches" pattern="/^[a-z0-9][a-z0-9_\-]{1,49}$/i" />
		</property>

		<property name="label" stateless="true" />

		<property name="passwordHash" type="String" indexed="none" />

        <property name="hashMethod" type="String" indexed="none">
            <dboptions length="20" />
        </property>

		<property name="groups" type="DocumentArray" document-type="Rbs_User_Group" />

		<property name="password" type="String" stateless="true">
			<constraint name="maxSize" max="50" />
		</property>

	</properties>
</document>

=== Darathor/Change/Plugins/Modules/Rbs/Commerce/Documents/Assets/Profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd">
	<properties>
		<property name="user" type="Document" document-type="Rbs_User_User"/>
		<property name="lastCartIdentifier" type="String" />
		<property name="defaultWebStore" type="Document" document-type="Rbs_Store_WebStore" />
		<property name="defaultZone" type="String" />
		<property name="defaultBillingArea" type="Document" document-type="Rbs_Price_BillingArea" />
		<property name="defaultBillingAddress" type="Document" document-type="Rbs_Geo_Address" />
		<property name="defaultShippingAddress" type="Document" document-type="Rbs_Geo_Address" />
	</properties>
</document>

=== Darathor/Change/ChangeTests/Change/Documents/Generators/TestAssets/TestInline.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"
		  localized="true" activable="true" editable="true">
	<properties>
		<property name="items" type="InlineArray" has-correction="true">
			<inline name="TestInlineItem" localized="true" activable="true" editable="true">
				<properties>
					<property name="title" type="String" localized="true"/>
					<property name="description" type="RichText" localized="true"/>
					<property name="visual" type="Document" document-type="Rbs_Media_Image"/>
					<property name="targetUrl" type="String" localized="true"/>
					<property name="extendedData" type="JSON" />
				</properties>
			</inline>
		</property>

		<property name="detail" type="Inline" has-correction="true">
			<inline>
				<properties>
					<property name="title" type="String"/>
					<property name="description" type="RichText"/>
					<property name="visual" type="Document" document-type="Rbs_Media_Image"/>
					<property name="targetUrl" type="String"/>
					<property name="targetDocument" type="Document"/>
					<property name="extendedData" type="JSON" />
				</properties>
			</inline>
		</property>
	</properties>
</document>

=== Darathor/Change/ChangeTests/UnitTestWorkspace/App/Modules/Project/Tests/Documents/Assets/Inline.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 https://raw.github.com/RBSChange/Change/master/Change/Documents/Assets/document.xsd">
	<properties>
		<property name="pInline" type="Inline">
			<inline>
				<properties>
					<property name="test" type="String"/>
				</properties>
			</inline>
		</property>

		<property name="pInlineArray" type="InlineArray">
			<inline>
				<properties>
					<property name="test" type="String"/>
					<property name="number" type="Integer"/>
				</properties>
			</inline>
		</property>
	</properties>
</document>

=== Darathor/Change/Plugins/Modules/Rbs/Website/Documents/Assets/Menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"
	localized="true" activable="true" editable="true">
	<properties>
		<property name="website" type="Document" document-type="Rbs_Website_Website" required="true" />
		<property name="entries" type="InlineArray" has-correction="true">
			<inline name="MenuEntry" localized="true" editable="true">
				<properties>
					<property name="title" type="String" localized="true" />
					<property name="entryTypeCode" type="String" required="true" />
					<property name="targetDocument" type="Document" />
					<property name="url" type="String" localized="true" />
					<property name="subMenu" type="Document" />
				</properties>
			</inline>
		</property>
		<property name="title" type="String" localized="true" has-correction="true" />
	</properties>
</document>

=== Darathor/Change/Plugins/Modules/Rbs/Theme/Documents/Assets/Template.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"
		activable="true" editable="true">
	<properties>
		<property name="code" type="String" required="true" />
		<property name="htmlData" type="LongString" />
		<property name="htmlForBackoffice" type="LongString" />
		<property name="editableContent" type="JSON" />
		<property name="theme" type="Document" document-type="Rbs_Theme_Theme" />
		<property name="contentByWebsite" type="JSON" />
		<property name="mailSuitable" type="Boolean" default-value="false" />
	</properties>
</document>

=== Darathor/Change/Plugins/Modules/Rbs/Catalog/Documents/Assets/Price.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd" 
	icon="folder" localized="true" editable="true" publishable="true" tree-name="Rbs_Catalog">
	<properties>
		<property name="product" type="Document" document-type="Rbs_Catalog_AbstractProduct" required="true" />
		<property name="shop" type="Document" document-type="Rbs_Catalog_Shop" required="true" />
		<property name="billingArea" type="Document" document-type="Rbs_Catalog_BillingArea" required="true" />
		<property name="targetId" type="DocumentId" required="true" default-value="0" />
		<property name="thresholdMin" type="Integer" required="true" default-value="1" />
		<property name="priority" type="Integer" required="true" default-value="25" />
		<property name="storeWithTax" type="Boolean" default-value="false" />
		<property name="taxCategory" type="String" required="true" default-value="0" />
		<property name="value" type="Float" required="true" />
		<property name="valueWithoutDiscount" type="Float" />
		<property name="discountDetail" type="String" />
		<property name="ecoTax" type="Float" required="true" default-value="0" />
	</properties>
</document>

=== Darathor/Change/Plugins/Modules/Rbs/Geo/Documents/Assets/Zone.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.rbs.fr/schema/change-document/4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.rbs.fr/schema/change-document/4.0 http://www.rbschange.fr/schema/4.0/document.xsd"
	editable="true" localized="true">
	<properties>
		<property name="title" type="String" localized="true" />

		<property name="code" type="String">
			<dboptions length="80" />
			<constraint name="unique" />
		</property>
		<property name="country" type="Document" document-type="Rbs_Geo_Country" />
		<property name="addressFilterData" type="JSON" />

		<property name="filterErrorMessage" type="LongString" localized="true" />
	</properties>
</document>
